version: '3.8'

services:
  db:
    container_name: parking_app_db
    image: postgres
    restart: always
    ports:
      - 2010:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres_parking_app
      POSTGRES_PASSWORD: password
    volumes:
      - db_data_parking_app:/var/lib/postgresql/data

volumes:
  db_data_parking_app:
